name: 🐰 Bunny Stats Hunter

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout do repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}
        
      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: 📦 Instalar dependências
        run: npm install
        
      - name: 🐰 Rodar Bunny Hunter
        run: node src/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ github.repository_owner }}
          
      - name: 📤 Commit e Push
        uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          commit_message: "🐰 Caça diária atualizada"
          commit_user_name: "Bunny Hunter Bot"
          commit_user_email: "bunny@blue-lock.com"
          commit_author: "Bunny Hunter Bot <bunny@blue-lock.com>"
